#include "../include/entropy.h"

static int	is_positive_number(const char *s)
{
	int		i = 0;
	long	v = 0;

	if (s == NULL)
		return 0;
	if (s[0] == '\0')
		return 0;

	while (s[i])
	{
		if (!isdigit((unsigned char)s[i]))
			return 0;
		i++;
	}
	v = atol(s);
	if (v <= 0)
		return 0;
	return 1;
}

static void print_usage(const char *prog)
{
    fprintf(stderr, CLR_RED "Uso: %s <nthreads> <per_thread>\n\t<nthreads> : total number of threads (>0)\n\t<per_thread>: number of integers generated by each thread (>0)\n" CLR_END, prog ? prog : "program");
}

int	main(int argc, char **argv)
{
	world_t	world;

	if (argc != 3)
	{
		print_usage(argc > 0 ? argv[0] : "program");
		return 1;
	}
	if (!is_positive_number(argv[1]) || !is_positive_number(argv[2]))
	{
		print_usage(argv[0]);
		return 1;
	}

	world.nthreads = atoi(argv[1]);
	world.per_thread = atoi(argv[2]);

	if (!world_init(&world, world.nthreads, world.per_thread))
	{
		fprintf(stderr, CLR_RED "Error: world_init failed\n" CLR_END);
		return 1;
	}
	world_launch(&world);
	world_show_results(&world);
	world_print_and_cleanup(&world);
	return 0;
}
